const resources = Object.freeze({
  en: Object.freeze({
    "app.title": "Clackly",
    "settings.title": "Clackly Settings",
    "settings.label": "Settings",
    "settings.close": "Close Settings",
    "settings.general": "General",
    "settings.application": "Clackly Settings",
    "settings.features": "Features",
    "settings.searchFeatures": "Search Features",
    "settings.searchFeatures.placeholder": "Search Features",
    "settings.searchEmpty": "No matching Features.",
    "settings.current": "Current",
    "settings.language": "Language",
    "settings.language.help": "Choose the language used throughout Clackly.",
    "settings.language.system": "System Default",
    "settings.language.en": "English",
    "settings.language.zh-CN": "Simplified Chinese",
    "settings.loading": "Loading features…",
    "settings.unavailable": "Unable to load features",
    "settings.none": "No features registered",
    "settings.none.detail": "Registered capability metadata will appear here automatically.",
    "settings.saved": "Settings saved.",
    "settings.reset": "Settings reset.",
    "settings.selectionCancelled": "Selection cancelled.",
    "settings.enabled": "Feature enabled.",
    "settings.disabled": "Feature disabled.",
    "settings.refreshed": "Feature status refreshed.",
    "settings.featureStatus": "Feature Status",
    "settings.ready": "Ready to use.",
    "settings.refresh": "Refresh",
    "settings.enable": "Enable",
    "settings.disable": "Disable",
    "settings.installed": "Installed",
    "settings.enabledLabel": "Enabled",
    "settings.readiness": "Readiness",
    "settings.missing": "Missing",
    "settings.yes": "Yes",
    "settings.no": "No",
    "settings.configuration": "Configuration",
    "settings.about": "About",
    "settings.status": "Status",
    "settings.interaction": "Interaction",
    "settings.contextInspector": "Context Inspector",
    "settings.version": "Version",
    "settings.providers": "Providers",
    "settings.applicationDescription": "Clackly is a compact command instrument for DaVinci Resolve.",
    "settings.status.checking": "Checking",
    "settings.status.checking.reason": "Checking feature availability…",
    "settings.status.disabled": "Disabled",
    "settings.status.disabled.reason": "This Feature is disabled.",
    "settings.status.ready": "Ready",
    "settings.status.needsSetup": "Needs Setup",
    "settings.status.missingConfig.reason": "Required configuration is missing.",
    "settings.status.missingDependency.reason": "A required dependency is unavailable.",
    "settings.status.unavailable": "Unavailable",
    "settings.status.unavailable.reason": "This Feature is unavailable.",
    "settings.error.load": "Could not load Settings data. Try again.",
    "settings.error.configLoad": "Could not load this Feature's settings. Select the Feature again or try again.",
    "settings.error.pathPicker": "Could not open the file picker. Try again.",
    "settings.error.save": "Could not save settings. Review the fields and try again.",
    "settings.error.reset": "Could not reset settings. Try again.",
    "settings.error.refresh": "Could not refresh Feature status. Try again.",
    "settings.error.enable": "Could not enable this Feature. Try again.",
    "settings.error.disable": "Could not disable this Feature. Try again.",
    "settings.error.locale": "Could not change the language. Try again.",
    "settings.interactionHelp": "Interaction Help",
    "settings.noInteractionHelp": "No interaction help available.",
    "settings.resetButton": "Reset",
    "settings.save": "Save",
    "settings.working": "Working…",
    "settings.noSettings": "No settings required.",
    "settings.selectOption": "Select an option",
    "settings.browse": "Browse",
    "palette.launcher": "Launcher",
    "palette.search": "Search commands",
    "palette.searchPlaceholder": "Search commands",
    "palette.searchPlaceholderLauncher": "Search commands…",
    "palette.commands": "Commands",
    "palette.results": "Results",
    "palette.pinned": "Pinned",
    "palette.recent": "Recent",
    "palette.noCommands": "No commands registered",
    "palette.noCommands.detail": "Registered command metadata will appear here automatically.",
    "palette.noResults": "No matching commands",
    "palette.noResults.detail": "Try another command name or editing verb.",
    "palette.running": "Running command…",
    "palette.settings": "Settings",
    "palette.pin": "Pin {name}",
    "palette.unpin": "Unpin {name}",
    "palette.pinSelected": "Pin selected command",
    "palette.pinnedStatus": "Pinned",
    "palette.openInfo": "Open interaction info",
    "palette.closeInfo": "Close interaction info",
    "palette.commandInfo": "Command information",
    "palette.panelUnavailable": "Interaction panel is unavailable.",
    "interaction.ariaLabel": "Command information",
    "interaction.rowAria": "{label}: {actionName}",
    "interaction.preview": "Preview only — commands run in Electron.",
    "interaction.click": "Click",
    "interaction.rightClick": "Right Click",
    "interaction.ctrl": "Ctrl",
    "interaction.shift": "Shift",
    "interaction.alt": "Alt",
    "status.warning.loading": "Checking feature availability…",
    "status.warning.disabled": "Feature is disabled.",
    "status.warning.unavailable": "Feature is unavailable.",
    "status.warning.missing-config": "Needs setup",
    "status.warning.missing-dependency": "Missing dependency",
    "status.warning.error": "Feature is unavailable.",
    "status.label.loading": "Loading",
    "status.label.disabled": "Disabled",
    "status.label.unavailable": "Unavailable",
    "status.label.ready": "Ready",
    "status.label.missing-config": "Needs setup",
    "status.label.missing-dependency": "Missing dependency",
    "status.label.error": "Unavailable",
    "error.generic": "The command could not be completed.",
    "error.clipboard-image-not-found": "No image was found in the Clipboard.",
    "error.clipboard-image-read-failed": "Clackly could not read the Clipboard image.",
    "error.clipboard-image-save-failed": "Clackly could not save the Clipboard image.",
    "error.clipboard-image-path-unsafe": "Clackly could not prepare a safe image location.",
    "error.resolve-project-unavailable": "Open a Resolve project, then try again.",
    "error.media-pool-import-failed": "Resolve could not import the Clipboard image.",
    "native.hotkey.title": "Clackly",
    "native.hotkey.message": "Clackly could not register {accelerator}.",
    "native.hotkey.detail": "Another process is already using the global shortcut. Close any old Clackly process, then reload Clackly from Resolve.",
    "fallback": "Unavailable"
  }),
  "zh-CN": Object.freeze({
    "app.title": "Clackly",
    "settings.title": "Clackly 设置",
    "settings.label": "设置",
    "settings.close": "关闭设置",
    "settings.general": "通用",
    "settings.application": "Clackly 设置",
    "settings.features": "功能",
    "settings.searchFeatures": "搜索功能",
    "settings.searchFeatures.placeholder": "搜索功能",
    "settings.searchEmpty": "没有匹配的功能。",
    "settings.current": "当前功能",
    "settings.language": "语言",
    "settings.language.help": "选择 Clackly 全界面使用的语言。",
    "settings.language.system": "跟随系统",
    "settings.language.en": "English",
    "settings.language.zh-CN": "简体中文",
    "settings.loading": "正在载入功能…",
    "settings.unavailable": "无法载入功能",
    "settings.none": "没有已注册功能",
    "settings.none.detail": "已注册的功能元数据会自动显示在这里。",
    "settings.saved": "设置已保存。",
    "settings.reset": "设置已重置。",
    "settings.selectionCancelled": "已取消选择。",
    "settings.enabled": "功能已启用。",
    "settings.disabled": "功能已停用。",
    "settings.refreshed": "功能状态已刷新。",
    "settings.featureStatus": "功能状态",
    "settings.ready": "可以使用。",
    "settings.refresh": "刷新",
    "settings.enable": "启用",
    "settings.disable": "停用",
    "settings.installed": "已安装",
    "settings.enabledLabel": "已启用",
    "settings.readiness": "就绪状态",
    "settings.missing": "缺失项",
    "settings.yes": "是",
    "settings.no": "否",
    "settings.configuration": "配置",
    "settings.about": "关于",
    "settings.status": "状态",
    "settings.interaction": "交互",
    "settings.contextInspector": "上下文检查器",
    "settings.version": "版本",
    "settings.providers": "提供方",
    "settings.applicationDescription": "Clackly 是适用于 DaVinci Resolve 的紧凑命令工具。",
    "settings.status.checking": "检查中",
    "settings.status.checking.reason": "正在检查功能可用性…",
    "settings.status.disabled": "已停用",
    "settings.status.disabled.reason": "此功能已停用。",
    "settings.status.ready": "已就绪",
    "settings.status.needsSetup": "需要设置",
    "settings.status.missingConfig.reason": "缺少必要配置。",
    "settings.status.missingDependency.reason": "必要依赖项不可用。",
    "settings.status.unavailable": "不可用",
    "settings.status.unavailable.reason": "此功能不可用。",
    "settings.error.load": "无法载入设置数据，请重试。",
    "settings.error.configLoad": "无法载入此功能的设置，请重新选择该功能后重试。",
    "settings.error.pathPicker": "无法打开文件选择器，请重试。",
    "settings.error.save": "无法保存设置，请检查字段后重试。",
    "settings.error.reset": "无法重置设置，请重试。",
    "settings.error.refresh": "无法刷新功能状态，请重试。",
    "settings.error.enable": "无法启用此功能，请重试。",
    "settings.error.disable": "无法停用此功能，请重试。",
    "settings.error.locale": "无法更改语言，请重试。",
    "settings.interactionHelp": "交互帮助",
    "settings.noInteractionHelp": "没有可用的交互帮助。",
    "settings.resetButton": "重置",
    "settings.save": "保存",
    "settings.working": "处理中…",
    "settings.noSettings": "无需设置。",
    "settings.selectOption": "选择一个选项",
    "settings.browse": "浏览",
    "palette.launcher": "启动器",
    "palette.search": "搜索命令",
    "palette.searchPlaceholder": "搜索命令",
    "palette.searchPlaceholderLauncher": "搜索命令…",
    "palette.commands": "命令",
    "palette.results": "结果",
    "palette.pinned": "已固定",
    "palette.recent": "最近使用",
    "palette.noCommands": "没有已注册命令",
    "palette.noCommands.detail": "已注册的命令元数据会自动显示在这里。",
    "palette.noResults": "没有匹配命令",
    "palette.noResults.detail": "请尝试其他命令名称或剪辑操作。",
    "palette.running": "正在运行命令…",
    "palette.settings": "设置",
    "palette.pin": "固定 {name}",
    "palette.unpin": "取消固定 {name}",
    "palette.pinSelected": "固定所选命令",
    "palette.pinnedStatus": "已固定",
    "palette.openInfo": "打开交互信息",
    "palette.closeInfo": "关闭交互信息",
    "palette.commandInfo": "命令信息",
    "palette.panelUnavailable": "交互面板不可用。",
    "interaction.ariaLabel": "命令信息",
    "interaction.rowAria": "{label}：{actionName}",
    "interaction.preview": "仅预览 — 命令会在 Electron 中运行。",
    "interaction.click": "单击",
    "interaction.rightClick": "右键单击",
    "interaction.ctrl": "Ctrl",
    "interaction.shift": "Shift",
    "interaction.alt": "Alt",
    "status.warning.loading": "正在检查功能可用性…",
    "status.warning.disabled": "功能已停用。",
    "status.warning.unavailable": "功能不可用。",
    "status.warning.missing-config": "需要设置",
    "status.warning.missing-dependency": "缺少依赖项",
    "status.warning.error": "功能不可用。",
    "status.label.loading": "正在载入",
    "status.label.disabled": "已停用",
    "status.label.unavailable": "不可用",
    "status.label.ready": "已就绪",
    "status.label.missing-config": "需要设置",
    "status.label.missing-dependency": "缺少依赖项",
    "status.label.error": "不可用",
    "error.generic": "无法完成该命令。",
    "error.clipboard-image-not-found": "剪贴板中没有图像。",
    "error.clipboard-image-read-failed": "Clackly 无法读取剪贴板图像。",
    "error.clipboard-image-save-failed": "Clackly 无法保存剪贴板图像。",
    "error.clipboard-image-path-unsafe": "Clackly 无法准备安全的图像位置。",
    "error.resolve-project-unavailable": "请打开一个 Resolve 项目后重试。",
    "error.media-pool-import-failed": "Resolve 无法导入剪贴板图像。",
    "native.hotkey.title": "Clackly",
    "native.hotkey.message": "Clackly 无法注册 {accelerator}。",
    "native.hotkey.detail": "全局快捷键正在被其他进程使用。请关闭旧的 Clackly 进程，然后从 Resolve 重新载入 Clackly。",
    "fallback": "不可用"
  })
});

function interpolate(value, params = {}) {
  return value.replace(/\{([A-Za-z0-9_]+)\}/g, (_match, key) => {
    const param = params[key];
    return ["string", "number", "boolean"].includes(typeof param) ? String(param) : "";
  });
}

function translate(locale, key, params) {
  const selected = resources[locale] || resources.en;
  const value = selected[key] || resources.en[key] || resources.en.fallback;
  return interpolate(value, params);
}

export { resources, translate };
